esphome:
  name: test2
  friendly_name: test2

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "9AvK6/vwfxYzLhRqUVxDCqdu4mSw5aRk0QBlrrm/kgQ="

ota:
  - platform: esphome
    password: "da43e90c3de59987c9a7d6be4552d742"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test2 Fallback Hotspot"
    password: "DC6gXGcTHpmM"


output:
  - platform: gpio
    pin: GPIO2   
    id: external_led

switch:
  - platform: output
    output: external_led
    name: "External LED"
    id: led_switch

interval:
  - interval: 1s
    then:
      - switch.toggle: led_switch

status_led:
  pin:
    number: GPIO21
    inverted: true